---
layout: post
title: 3-7. reduce에 대한 질문과 리팩토링
category: Functional-programming
permalink: /Functional-programming/:title/

tags: [함수형 프로그래밍]
comments: true
---

>프로그래머스에서 진행한 유인동님의 [ES6로 알아보는 동시성 & 함수형 프로그래밍 강의](https://programmers.co.kr/learn/courses/3409)를 들으며 정리한 내용입니다.

## # `reduce()` 리팩토링. 재귀 제거
reduce 함수의 acc가 프로미스인 경우 .then체인 걸어주는 방식으로 바꾸면, 재귀를 돌지 않아도 된다

```js
/*
function reduce(f, coll, acc) {
  const iter = collIter(coll)
  acc = acc === undefined ? iter.next().value : acc
  return then2(acc, function recur(acc) {
    for(const a of iter) {
      acc = f(acc, a)
      if(acc instanceof Promise) return acc.then(recur)
    }
    return acc
  })
} */

function reduce(f, coll, acc) {
  const iter = collIter(coll)
  acc = acc === undefined ? iter.next().value : acc
  for(const a of iter) {
    acc = acc instanceof Promise ? acc.then(acc => f(acc, a)) : f(acc, a)
  }
  return acc
}

log(reduce((a, b) => a + b, {a:1, b:2, c:3})) // 6
log(reduce((a, b) => Promise.resolve(a + b), {a:1, b:2, c:3}, 10)) // 16
log(reduce((a, b) => a + b, {a:1, b:2, c:3}, Promise.resolve(100))) // 106
log(reduce((a, b) => Promise.resolve(a + b), {a:1, b:2, c:3}, Promise.resolve(1000))) // 1006
```

## # `gen()` 함수 제거
원래 제너레이터로 만든 이터러블이 재귀를 돌기위해 for...of를 빠져나가면, 이터러블이 가지고 있던 return메소드를 실행시켜 이터러블을 종료시켜버리는 문제가 있어서, gen함수로 제너레이터 함수들을 감싸줬었다 (제너레이터로 생성한 이터러블의 return 메소드를 감춰주며, 이터레이터 동작을 위임)

하지만 이제 재귀를 돌지 않기때문에 콜스택에서 빠져나갈일이 없다. 즉, for...of를 빠져나가 즉 이터러블의 return메서드가 실행되어 이터러블이 중간에 중단될일 이 없다. return메서드를 감춰주기 위해 사용하던 gen함수를 제거하자

```js
/*
var valuesIter = gen(function*(obj) {
  for (const k in obj) yield obj[k];
})

var entriesIter = gen(function*(obj) {
  for (const k in obj) yield [k, obj[k]];
}) */

function *valuesIter(obj) {
  for (const k in obj) yield obj[k];
}

function *entriesIter(obj) {
  for (const k in obj) yield [k, obj[k]];
}
```

## # `findVal(), findValC`리팩토링

gen함수를 제거 하고나면

* coll로 객체가 와서 valuesIter 제너레이터로 iter를 만들고
* 보조함수로 Promise가 와서 재귀를 돌아야 하는 경우에

재귀를 돌기위해 for...of를 빠져나갈 경우 iter가 중단되는 문제가 생긴다

> for...of를 while로 대체 하자

### `findVal()`

기존의 findVal에서는 재귀를 도는순간 이터러블이 종료되었기 때문에, 찾는 값이 이터러블의 첫번째 값이 아닌 이상 항상 undefined를 반환하는 문제가 있다

```js
/*
const findVal = curry((f, coll) => {
  const iter = collIter(coll)
  return function recur(res) {
    for (const a of iter) {
      if((res = f(a)) !== undefined) {
        return go(res, res => res !== undefined ? res : recur())
      }
    }
  } ()
}) */

var findVal = curry((f, coll) => {
  const iter = collIter(coll)
  return function recur(cur, res) {
    while((cur = iter.next()) && !cur.done) {
      if ((res = f(cur.value)) !== undefined) {
        return go(res, res => res !== undefined ? res : recur())
      }
    }
  } ()
})

go([1,2,3,4,5],
  findVal(a => Promise.resolve(a > 3 ? a : undefined)),
  log) // 4
go({a:1, b:2, c:3, d:4, e:5},
  findVal(a => Promise.resolve(a > 3 ? a : undefined)),
  log) // 4
```

### `findValC()`

findValC의 iter는 stepIter에게 동작을 위임하기 때문에 coll로 객체가 오고, 보조함수가 프로미스여도 문제는 없다.

하지만 코드의 일관성을 위해 리팩토링 하자

```js
/*
var findValC = curry((f, coll, limit = Infinity) => {
  const iter = stepIter(collIter(coll), limit)
  return new Promise(function recur (resolve) {
    let i = 0, j = 0
    for (const a of iter) {
      ++i
      go(a, f, 
        b => b === undefined ? undefined : resolve(b),
        _ => (i == ++j) ? iter.remain ? recur(resolve) : resolve() : undefined)
    }
  })
}) */

var findValC = curry((f, coll, limit = Infinity) => {
  const iter = stepIter(collIter(coll), limit)
  return new Promise(function recur (resolve) {
    let i = 0, j = 0, cur
    while((cur = iter.next()) && !cur.done) {
      ++i
      go(cur.value, 
        f, 
        b => b === undefined ? undefined : resolve(b),
        _ => (i == ++j) ? iter.remain ? recur(resolve) : resolve() : undefined)
    }
  })
})

go({a:1, b:2, c:3, d:4, e:5},
  findVal(a => time(a > 3 ? a : undefined)),
  log) // 4 --> 4초소요

go({a:1, b:2, c:3, d:4, e:5},
  nums => findValC(a => time(a > 3 ? a : undefined), nums, 5),
  log) // 4 --> 1초소요
```

